language: java
install: "mvn install -DskipTests=true"
script: "mvn -e clean test jacoco:report coveralls:report"
jdk:
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
  - openjdk12
  - openjdk13
  - openjdk14
  - openjdk15
  - openjdk16
